---

- name: Create Kubernetes nodes
  hosts: m1
  gather_facts: false
  # roles:
    # - prelude
  vars:
    host_ip: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
  tasks:
    - name: test connection
      wait_for:
        host: 192.168.56.121
        port: 6443
        timeout: 3
      ignore_errors: yes
      register: test_conn

    - debug:
        msg: '{{host_ip}}'

