---

- name: Create Kubernetes nodes
  hosts: m1
  gather_facts: false
  # roles:
    # - prelude
  tasks:
    - name: Get admin config
      slurp:
        src: /etc/kubernetes/admin.conf
      register: admin_conf
      become: true
      run_once: true
      delegate_to: "{{ groups['master'][0]}}"

    - name: Create a directory if it does not exist
      local_action:
        module: ansible.builtin.file
        path: ~/.kube
        state: directory
      become: false
      run_once: true

    - name: Save admin config to local
      become: false
      local_action:
        module: ansible.builtin.copy
        dest: ~/.kube/vagrant-conf
        content: '{{ admin_conf.content | b64decode }}'
      run_once: true

    - debug:
        msg: '{{ admin_conf.content | b64decode }}'

