---

- name: Create Kubernetes nodes
  hosts: node
  become: yes
  gather_facts: false
  # roles:
    # - prelude
  tasks:
    - name: Get add node command
      shell: kubeadm token  create  --print-join-command
      register: add_command
      delegate_to: "{{ groups['master'][0]}}"

    - name: run add command
      shell: "{{add_command.stdout_lines[0]}}"


    # - name: download flannel
      # ansible.builtin.get_url:
        # url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        # dest: ~/flannel.yaml
        # mode: '0664'
#
    # - name: Apply flannel
      # kubernetes.core.k8s:
        # kubeconfig: /etc/kubernetes/admin.conf
        # state: present
        # src: ~/flannel.yaml
